Added import possibilities
Resplandy/climate-hpc pull request #2
Opened 2019-11-01 20:42 UTC by jbusecke

2019-11-01 20:50 UTC, luet requested changes

2019-11-01 20:50 UTC, luet commented on README.md
> +scp ~/Downloads/<yourfile> <username>@tigressdata.princeton.edu:/tigress/<username>/`
There is an extraneous ` at the end of that line

2019-11-01 20:50 UTC, luet commented on README.md
> +scp ~/Downloads/<yourfile> tigressdata:/tigress/<username>/`
same problem here

2019-11-01 20:52 UTC, luet commented
How is the user downloading the data on their own machine? Is through a web browser? If so why not use a web browser on tigressdata through TurboVNC?

2019-11-01 21:00 UTC, jbusecke commented
Yeah, that is a valid point. But that will be very different in each case. I actually don't know how to do that via TurboVCN. I might learn something hahaha

2020-01-24 15:58 UTC, jbusecke commented
Is this still of interest? Or should I close?

2020-01-24 19:19 UTC, cses commented
I added the section in this PR in commit 12707bf.

2020-01-24 19:24 UTC, luet commented
I added the section in this PR in commit 12707bf.

2020-01-24 19:24 UTC, closed without merging